// @flow
import { check } from 'express-validator';

export const postTagValidation = [
  check('time')
    .not()
    .isEmpty()
    .isString(),
  check('deviceId')
    .not()
    .isEmpty()
    .isString(),
  check('tags')
    .not()
    .isEmpty()
    .isArray(),
  check('tags.*.id')
    .not()
    .isEmpty()
    .isString(),
  check('tags.*.url')
    .not()
    .isEmpty()
    .isString(),
  check('tags.*.rssi')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.updateAt')
    .not()
    .isEmpty()
    .isString(),
  check('tags.*.dataFormat')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.name')
    .not()
    .isEmpty()
    .isString(),
  check('tags.*.temperature')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.humidity')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.pressure')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.accelX')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.accelY')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.accelZ')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.voltage')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.txPower')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.movementCounter')
    .not()
    .isEmpty()
    .isNumeric(),
  check('tags.*.measurementSequenceNumber')
    .not()
    .isEmpty()
    .isNumeric(),
  check('eventId')
    .not()
    .isEmpty()
    .isString(),
];
